name: List Actifacts
on:
  workflow_run:
    workflows: ["Generate Artifacts"]
    types: [completed]

jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List artifacts
        id: list-artifacts
        uses: chiaretto/github-action-list-artifacts-pr@branch1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Print variables
        run: |
          echo rit-linux: ${{ steps.list-artifacts.outputs.rit-linux }}